In [55]:
import numpy as np
import string 
import re

In [56]:
text = "War is a 2019 Indian Hindi-language action thriller film directed by Siddharth Anand. It is produced by Aditya Chopra under his banner Yash Raj Films, and stars Hrithik Roshan and Tiger Shroff. The film follows an Indian soldier assigned to eliminate his former mentor who has gone rogue. "

In [57]:
samples = re.sub(pattern=r'[^\w\s]', repl = ', ', string = text)

In [58]:
character = string.printable
print(len(text))

289


In [59]:
token_index = dict(zip(range(1, len(character) + 1), character))

In [60]:
max_length = 50

In [61]:
results = np.zeros((len(samples), max_length, max(token_index.keys()) + 1))
print(results.shape)

(294, 50, 101)


In [68]:
for i, sample in enumerate(samples):
    for j, character in enumerate(sample):
        index = token_index.get(character)
        results[i, j, index] = 1

In [72]:
print(results[0])

[[1. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
