# Character level one hot encoding ( Vectorizaton process)
#### document > cleaning data > tokenization > build vocabulary > vectorization (Using numpy)
### one-hot hashing trick is one of the maintain an word index with too large data to handle b/c it is light weight function.

In [58]:
import numpy as np
import string
import re

In [59]:
text = "As has already been mentioned, 1D convolutional neural nets can be used for extracting local 1D patche from sequences and can identify local patterns within the window of convolution. And because the same transformation is applied on every patch identified by the window, a pattern learnt at one position can also be recognized at a different position, making 1D conv nets translation invariant"

### cleaning data : removing punctuation

In [60]:
# \w = a-Z and 0-9 and _
# \s = accept white space character
text = re.sub(pattern = r'[^\w\s]', repl=', ', string=text)

###  Split  by , for tokenization

In [64]:
samples = text.split(', ')
samples

['As has already been mentioned',
 ' 1D convolutional neural nets can be used for extracting local 1D patche from sequences and can identify local patterns within the window of convolution',
 ' And because the same transformation is applied on every patch identified by the window',
 ' a pattern learnt at one position can also be recognized at a different position',
 ' making 1D conv nets translation invariant']

In [63]:
# fetch the printable character : 0-9, a-Z, punctuation
characters = string.printable

#print(len(characters))

token_index = dict(zip(range(1, len(characters) + 1), characters))

### Create dummy vector fill by 0

In [92]:
# let word in a sentence is 10
max_length = 50 
results = np.zeros(shape=(len(samples), max_length, max(token_index.values()) + 1))
#esults = np.arange(24).reshape(2, 3, 4)

### Dummy vector is filled by original value

In [93]:
for i, sample in enumerate(samples):
    #print(i, ' : ', sample)
    #break
    for j, word in list(enumerate(sample.split()))[:max_length]:
        index = token_index.get(word)
        results[i, j, index] = 1 # one hot so assign by 1

In [94]:
print(results)

[[[0. 1. 0. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 1. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
