# Word level one hot encoding (Vectorization way)
#### document > cleaning data > tokenization > build vocabulary > vectorization (Using numpy)

In [7]:
import numpy as np
import re

In [8]:
#text = "As has already been mentioned, 1D convolutional neural nets can be used for extracting local 1D patche from sequences and can identify local patterns within the window of convolution. And because the same transformation is applied on every patch identified by the window, a pattern learnt at one position can also be recognized at a different position, making 1D conv nets translation invariant"

text = "the the one one one"

### cleaning data : removing punctuation

In [9]:
# \w = a-Z and 0-9 and _
# \s = accept white space character
text = re.sub(pattern = r'[^\w\s]', repl=', ', string=text)

### tokenization = Split  by , 

In [10]:
samples = text.split(', ')

### Indexing

In [11]:
token_index = {}

for sample in samples:
    for word in sample.split():
        if word not in token_index :
            token_index[word] = len(token_index)+1

#print(token_index) # see value
#print(len(token_index)) # see length
#print(max(token_index.values())) #see max length

In [12]:
print(len(samples))

1


<ul class="list-group">
  <li class="list-group-item active"> <h1> Define vector fill by 0 <h1> </li>
  <li class="list-group-item">5X10X51 = Dimension of 5 sentence is 10X51</li>
  <li class="list-group-item">Morbi leo risus</li>
  <li class="list-group-item">Porta ac consectetur ac</li>
  <li class="list-group-item">Vestibulum at eros</li>
</ul>

In [13]:
max_length = 10 
results = np.zeros(shape=(len(samples), max_length, max(token_index.values()) + 1))
#esults = np.arange(24).reshape(2, 3, 4)

### Dummy vector is filled by original value

In [14]:
for i, sample in enumerate(samples):
    #print(i, ' : ', sample)
    #break
    for j, word in list(enumerate(sample.split()))[:max_length]:
        index = token_index.get(word)
        results[i, j, index] = 1 # one hot so assign by 1

In [15]:
#print(results)
# vector of first sentence
print(results[0, :, :])

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
